name: Deploy to Production

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Yandex Cloud CLI
        run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

      - name: Add Yandex Cloud CLI to $PATH
        run: echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Init Yandex Cloud CLI
        run: |
          yc config profile create utd-bot
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
          yc config set token ${{ secrets.YC_TOKEN }}
          yc container registry configure-docker

      - name: Build container
        run: make docker-build

      - name: Push container
        run: make docker-push

      - name: Deploy container
        run: make docker-deploy
